FROM python:3.12-slim

COPY requirements.txt /
COPY local_requirements.txt /
COPY concierge_packages/concierge_util /concierge_packages/concierge_util
COPY concierge_packages/isi_util /concierge_packages/isi_util

RUN --mount=type=cache,target=/root/.cache/pip pip install -r local_requirements.txt

COPY . /
CMD [ "python", "docker_run.py" ]

EXPOSE 15130