name: concierge

services:
  ollama:
    extends:
      file: launcher_package/src/launch_concierge/docker_compose/docker_compose_dependencies/docker-compose-ollama.yml
      service: ollama-gpu
  opensearch-node1:
    extends:
      file: launcher_package/src/launch_concierge/docker_compose/docker_compose_dependencies/docker-compose-opensearch.yml
      service: opensearch-node-disable-security
  opensearch-dashboards:
    extends:
      file: launcher_package/src/launch_concierge/docker_compose/docker_compose_dependencies/docker-compose-opensearch.yml
      service: opensearch-dashboards-disable-security
  concierge:
    extends:
      file: docker_compose_dependencies/docker-compose-concierge-local.yml
      service: concierge

volumes:
  opensearch-data1:

networks:
  default:
    name: concierge
