[project]
name = "shabti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit==4.6.2",
    "pre-commit-uv==4.3.0",
    "pytest==9.1.1",
    "pytest-asyncio==1.4.0",
    "ruff==0.16.4",
]

[tool.uv.workspace]
members = [
    "shiny_demo_projects",
]
