FROM astral/uv:0.11.1-python3.14-trixie-slim AS base

COPY --from=python_packages ./isi_util /app/python_packages/isi_util/
COPY --from=python_packages ./shabti_util /app/python_packages/shabti_util/
COPY --from=python_packages ./shabti_types /app/python_packages/shabti_types/
COPY --from=python_packages ./shabti_keycloak /app/python_packages/shabti_keycloak/
COPY --from=python_packages ./shabti_api_client /app/python_packages/shabti_api_client/

EXPOSE 15131
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/
WORKDIR /app/shabti/
ENV UV_LINK_MODE=copy
ENV UV_HTTP_TIMEOUT=500
CMD [ "uv", "run", "docker_run.py", "--development" ]

RUN --mount=type=cache,target=/root/.cache/uv --mount=type=bind,source=pyproject.toml,target=pyproject.toml uv sync --no-install-project

COPY . /app/shabti/

RUN --mount=type=cache,target=/root/.cache/uv uv sync --locked

RUN --mount=type=cache,target=/root/.cache uv pip install -r local_requirements.txt

# install packages so we can run pytest on them
WORKDIR /app/python_packages/isi_util/
RUN --mount=type=cache,target=/root/.cache/uv uv sync

WORKDIR /app/python_packages/shabti_api_client/
RUN --mount=type=cache,target=/root/.cache/uv uv add --editable ../isi_util/ ../shabti_types/
RUN --mount=type=cache,target=/root/.cache/uv uv sync

WORKDIR /app/shabti/


