[project]
name = "shabti-api"
version = "0.1.0"
requires-python = ">=3.14, <3.15"
dependencies = [
    "beautifulsoup4~=4.14.3",
    "configobj~=5.0.9",
    "fastapi[standard]~=0.119.0",
    "langchain~=1.2.10",
    "langchain-community~=0.4.1",
    "langchain-unstructured~=1.0.1",
    "langchain-text-splitters~=1.1.1",
    "lxml~=6.0.1",
    "opensearch-py~=3.0.0",
    "python-json-logger~=3.3.0",
    "python-magic-bin~=0.4.14 ; sys_platform == 'win32'",
    "sentence-transformers~=5.2.3",
    "unstructured[all-docs]~=0.21.5",
    "aiofiles~=25.1.0"
]
[project.optional-dependencies]
cu126 = [
    "fastembed-gpu"
]
cpu = [
    "fastembed"
]
[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu126" },
  ],
]

[dependency-groups]
dev = [
    "pytest~=8.4.2",
    "pytest-asyncio~=1.2.0",
]

[tool.pytest.ini_options]
asyncio_mode="auto"
asyncio_default_fixture_loop_scope="function"
addopts = "--import-mode=importlib"
