FROM python:3.12

COPY requirements.txt /
COPY local_requirements.txt /
COPY python_packages/isi_util /python_packages/isi_util
COPY python_packages/concierge_util /python_packages/concierge_util
COPY python_packages/concierge_types /python_packages/concierge_types
COPY python_packages/concierge_api_client /python_packages/concierge_api_client
COPY python_packages/concierge_keycloak /python_packages/concierge_keycloak

RUN --mount=type=cache,target=/root/.cache/pip pip install -r local_requirements.txt

COPY . /
CMD [ "python", "docker_run.py" ]

EXPOSE 15130