name: shabti

services:
  volume-ownership-changer:
    extends:
      file: ./docker_compose_dependencies/docker-compose-llama-cpp.yml
      service: volume-ownership-changer
  huggingface-downloader:
    extends:
      file: ./docker_compose_dependencies/docker-compose-llama-cpp.yml
      service: huggingface-downloader

volumes:
  llama-cpp-models:

networks:
  default:
    name: shabti