name: shabti

services:
  llama-cpp:
    extends:
      file: ./docker_compose_dependencies/docker-compose-llama-cpp.yml
      service: llama-cpp-${SHABTI_COMPUTE:-cpu}

volumes:
  llama-cpp-models:

networks:
  default:
    name: shabti