name: shabti

include:
  - ../shabti_configurator/docker_compose/docker_compose_dependencies/${KEYCLOAK_SERVICE_FILE:-docker-compose-blank.yml}

services:
  llama-cpp:
    extends:
      file: ../shabti_configurator/docker_compose/docker_compose_dependencies/docker-compose-llama-cpp.yml
      service: llama-cpp-${SHABTI_COMPUTE:-cpu}
  opensearch-node1:
    extends:
      file: ../shabti_configurator/docker_compose/docker_compose_dependencies/docker-compose-opensearch.yml
      service: opensearch-node-base
  tika:
    extends:
      file: ../shabti_configurator/docker_compose/docker_compose_dependencies/docker-compose-tika.yml
      service: tika
  shabti:
    extends:
      file: ../shabti_configurator/docker_compose/docker_compose_dependencies/docker-compose-shabti.yml
      service: ${SHABTI_SERVICE:-shabti}
    build:
      context: ../docker_containers/shabti_api
      additional_contexts:
        python_packages: ../python_packages
      dockerfile: Dockerfile
      target: local
    restart: unless-stopped

volumes:
  opensearch-data1:
  llama-cpp-models:
  llama-cpp-cache:
  shabti-files:

networks:
  default:
    name: shabti