FROM astral/uv:0.11.1-python3.14-trixie-slim

COPY --from=python_packages ./shabti_util /app/python_packages/shabti_util/
COPY --from=python_packages ./shabti_types /app/python_packages/shabti_types/
COPY --from=python_packages ./shabti_keycloak /app/python_packages/shabti_keycloak/
COPY --from=python_packages ./shabti_api_client /app/python_packages/shabti_api_client/

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/
WORKDIR /app/shabti_web/
ENV UV_LINK_MODE=copy
RUN --mount=type=cache,target=/root/.cache/uv --mount=type=bind,source=pyproject.toml,target=pyproject.toml uv sync --no-install-project
COPY . /app/shabti_web/
RUN --mount=type=cache,target=/root/.cache/uv uv sync
RUN --mount=type=cache,target=/root/.cache uv pip install -r local_requirements.txt
CMD [ "uv", "run", "docker_run.py", "--development" ]

EXPOSE 15130