name: concierge

services:
  ollama:
    extends:
      file: docker_compose_dependencies/docker-compose-ollama.yml
      service: ${OLLAMA_SERVICE:-ollama}
  opensearch-node1:
    extends:
      file: docker_compose_dependencies/docker-compose-opensearch.yml
      service: ${OPENSEARCH_SERVICE:-opensearch-node-disable-security}
  concierge:
    extends:
      file: docker_compose_dependencies/docker-compose-concierge.yml
      service: concierge

volumes:
  opensearch-data1:
  ollama:

networks:
  default:
    name: concierge